---
title: "Regression for Larralde & Noveck E2 replication with disjunctions in training"
author: Morgan Moyer
date: 17 March, 2023
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(philentropy)
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
```

```{r read in all the data, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
d.raw.rt1 <- read.csv("../data/raw_rt1_processed.csv")
d.log.rt1 <- read.csv("../data/log_rt1_processed.csv")
```



```{r turn everthing into a factor, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}

# Make everything into a factor
d.raw.rt1$Connective = as.factor(d.raw.rt1$Connective)
d.raw.rt1$ID = as.factor(d.raw.rt1$ID)
d.raw.rt1$TrialID = as.factor(d.raw.rt1$TrialID)
d.raw.rt1$ReactionTime1 = as.numeric(d.raw.rt1$ReactionTime1)

# Make everything into a factor
d.log.rt1$Connective = as.factor(d.log.rt1$Connective)
d.log.rt1$ID = as.factor(d.log.rt1$ID)
d.log.rt1$TrialID = as.factor(d.log.rt1$TrialID)
d.log.rt1$ReactionTime1 = as.numeric(d.log.rt1$ReactionTime1)


# d.rt2$Connective = as.factor(d.rt2$Connective)
# d.rt2$ID = as.factor(d.rt2$ID)
# d.rt2$TrialID = as.factor(d.rt2$TrialID)
# d.rt2$ReactionTime2 = as.numeric(d.rt2$ReactionTime2)
# d.rt2$LogRT2 = log(d.rt2$ReactionTime2)
# d.rt2$Truthvalue = as.factor(d.rt2$Truthvalue)
# d.rt2$Sentenceform = as.factor(d.rt2$Sentenceform)

```


# Reaction Time 1
## Raw RT

```{r}
d.raw.rt1 <- d.raw.rt1 %>% 
  filter(Connective %in% c("and","but","so"))
m.raw.rt1 = lmer(ReactionTime1 ~ Connective + (1+Connective|ID) + (1|TrialID), data=d.raw.rt1)

summary(m.raw.rt1)

```

## LogRT
```{r}
d.log.rt1 <- d.log.rt1 %>% 
  filter(Connective %in% c("and","but","so"))

m.log.rt1 = lmer(LogReactionTime1 ~ Connective + (1+Connective|ID) + (1|TrialID), data=d.log.rt1)

summary(m.log.rt1)

```

