---
title: "Graphs for replication with dysjunction"
author: Morgan Moyer
date: May 12, 2022
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
```


```{r}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

d.raw.rt1 <- read.csv("../data/raw_rt1_processed.csv")
d.log.rt1 <- read.csv("../data/log_rt1_processed.csv")

# d.c <- read.csv("../data/preprocessed_cecile.csv")

# d.rt2 <- read.csv("../data/rt2_double_processed.csv")
```


# Looing at RT1 Cecile pre-processing

## Overall raw RT 1
```{r}
d.rt1.grand$ReactionTime1 <- as.numeric(d.rt1.grand$ReactionTime1)

agr <- d.rt1.grand %>%
  group_by(Connective) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

View(agr)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```



# Looing at RT1

## Overall raw RT 1
```{r}
d.rt1$ReactionTime1 <- as.numeric(d.rt1$ReactionTime1)

agr <- d.rt1 %>%
  group_by(Connective) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

View(agr)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```


## Overall Log RT1
```{r}
agr <- d.rt1 %>%
  group_by(Connective) %>%
  summarize(logRT1= log(ReactionTime1), meanLogRT = mean(logRT1), CILow = ci.low(logRT1), CIHigh = ci.high(logRT1)) %>% 
  mutate(YMin = meanLogRT - CILow, YMax = meanLogRT + CIHigh)


dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanLogRT, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```



## Connective x Truthvalue : raw RT 1
```{r}
d.rt1$ReactionTime1 <- as.numeric(d.rt1$ReactionTime1)

agr <- d.rt1 %>%
  filter(Connective %in% c("and","but","so"))%>% 
  group_by(Connective,Truthvalue) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Truthvalue, y=meanRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```


# Looing at RT2

## Overall RT2
```{r}
d.rt2$ReactionTime2 <- as.numeric(d.rt2$ReactionTime2)

agr <- d.rt2 %>%
  filter(Connective %in% c("and","but","so"))%>% 
  group_by(Connective) %>%
  summarize(meanRT2 = mean(ReactionTime2), CILow = ci.low(ReactionTime2), CIHigh = ci.high(ReactionTime2)) %>% 
  mutate(YMin = meanRT2 - CILow, YMax = meanRT2 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT2, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```




## Overall Log RT2
```{r}
agr <- d.rt2 %>%
  filter(Connective %in% c("and","but","so"))%>% 
  group_by(Connective) %>%
  summarize(logRT2= log(ReactionTime2), meanLogRT2 = mean(logRT2), CILow = ci.low(logRT2), CIHigh = ci.high(logRT2)) %>% 
  mutate(YMin = meanLogRT2 - CILow, YMax = meanLogRT2 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanLogRT2, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```


