---
title: "Graphs for replication with disjunctions in training"
author: Morgan Moyer
date: May 12, 2022
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")


```


```{r set wd and read in data, include=FALSE, warning=FALSE, echo=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

d <- read.csv("../data/log_rt1_processed.csv")
d$ReactionTime1 <- as.numeric(d$ReactionTime1)
d$LogReactionTime1 <- as.numeric(d$LogReactionTime1)

```

# Looing at RT1

## Overall raw RT 1
```{r}
agr <- d %>%
  group_by(Connective) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)

# ggsave("../graphs/Ex2_RawRT.pdf",width=6,height=4)
```

#Log RT
```{r}
agr <- d %>%
  group_by(Connective) %>%
  summarize(meanLogRT1 = mean(LogReactionTime1), CILow = ci.low(LogReactionTime1), CIHigh = ci.high(LogReactionTime1)) %>% 
  mutate(YMin = meanLogRT1 - CILow, YMax = meanLogRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanLogRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)

# ggsave("../graphs/Ex2_LogRT.pdf",width=6,height=4)
```


# Look at BinaryOrder

```{r}

agr <- d %>%
  group_by(Connective,OrderBinary) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT1, fill=OrderBinary)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)

# ggsave("../graphs/Ex2_OrderBinary.pdf",width=6,height=4)
```



# Look at OrderTrial

```{r}
d$OrderTrials <- as.factor(d$OrderTrials)

agr <- d %>%
  group_by(OrderTrials,Connective) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=OrderTrials, y=meanRT1, fill=Connective)) +
  # geom_point() +
  geom_smooth() +
  
  geom_dotplot(binaxis='y', stackdir='center',stackratio=1, dotsize=.7)
  # facet_wrap(~Connective)


```



