---
title: "Graphs for replication"
author: Morgan Moyer
date: May 12, 2022
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")


```


```{r set wd and read in data, include=FALSE, warning=FALSE, echo=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

d.raw.rt1 <- read.csv("../data/explorative_raw_rt1_processed.csv")
d.log.rt1 <- read.csv("../data/explorative_log_rt1_processed.csv")

names(d.log.rt1)


```

# Looing at RT1

## Overall raw RT 1
```{r}
# d.raw.rt1$ReactionTime1 <- as.numeric(d.raw.rt1$ReactionTime1)

agr <- d.raw.rt1 %>%
  filter(Connective %in% c("and","but","so"))%>% 
  group_by(Connective) %>%
  summarize(meanRT1 = mean(ReactionTime1), CILow = ci.low(ReactionTime1), CIHigh = ci.high(ReactionTime1)) %>% 
  mutate(YMin = meanRT1 - CILow, YMax = meanRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```


## Overall raw RT 1
```{r}
# d.log.rt1$LogReactionTime1 <- as.numeric(d.log.rt1$LogReactionTime1)

agr <- d.log.rt1 %>%
  filter(Connective %in% c("and","but","so"))%>% 
  group_by(Connective) %>%
  summarize(meanLogRT1 = mean(LogReactionTime1), CILow = ci.low(LogReactionTime1), CIHigh = ci.high(LogReactionTime1)) %>% 
  mutate(YMin = meanLogRT1 - CILow, YMax = meanLogRT1 + CIHigh)

dodge = position_dodge(.9)
ggplot(agr,aes(x=Connective, y=meanLogRT1, fill=Connective)) +
    geom_bar(position=dodge,stat="identity") +
    geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge)
```


