---
title: "Regression for Larralde & Noveck E2 replication with disjunctions in training"
author: Morgan Moyer
date: 17 March, 2023
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(philentropy)
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
```

```{r read in all the data, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)

d <- read.csv("../data/log_rt1_processed.csv")
```



```{r turn everthing into a factor, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}


# Make everything into a factor
d$Connective = as.factor(d$Connective)
d$ID = as.factor(d$ID)
# d$OrderBinary = as.factor(d$OrderBinary)
# d$OrderTrials = as.factor(d$OrderTrials)
d$TrialID = as.factor(d$TrialID)
d$ReactionTime1 = as.numeric(d$ReactionTime1)
d$LogReactionTime1 = as.numeric(d$LogReactionTime1)

```


# Reaction Time 1

## LogRT
```{r}

m.log.rt1 = lmer(LogReactionTime1 ~ Connective + (1+Connective|ID) + (1|TrialID), data=d)

summary(m.log.rt1)

```

## Log RT x OrderBinary
- interaction

```{r, eval = FALSE}
centered <- d %>% 
  mutate(cOrderBinary = as.numeric(OrderBinary)-mean(as.numeric(OrderBinary)))

m.order.binary = lmer(LogReactionTime1 ~ Connective*cOrderBinary + (1+Connective|ID) + (1|TrialID), data=centered)

summary(m.order.binary)

```

### Model on second half only

```{r, eval = FALSE}

d.second.half <- d %>% 
  filter(OrderBinary == "second")

m.log.rt1.second.half = lmer(LogReactionTime1 ~ Connective + (1+Connective|ID) + (1|TrialID), data=d.second.half)

summary(m.log.rt1.second.half)

```

## LogRT x OrderTrials
- Really hard to interpret, so better to do a chi-squared
```{r, eval = FALSE}
m.order.trials = lmer(LogReactionTime1 ~ Connective*OrderTrials + (1+Connective|ID) + (1|TrialID), data=d)

summary(m.order.trials)

```
### Does the model with OrderTrials explain more than the model without?

```{r, eval = FALSE}
anova(m.log.rt1,m.order.trials,test="Chisq")
```

